[project]
name = "kagenti_providers"
version = "0.1.0"
description = "Kagenti providers for LLama Stack"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-stack>=0.2.14", 
]

[tool.setuptools]
package-dir = { "" = "src" }
