apiVersion: kagenti.operator.dev/v1alpha1
kind: Component
metadata:
  name: acp-ollama-researcher
  labels:
     app.kubernetes.io/name: kagenti-operator
spec:
  description: "acp-ollama-researcher from ACP community"

  agent:
    # Optional build specification for building from source
    build:
      mode: dev
      pipeline:
        parameters:
          - name: github-token-secret
            value: "github-credentials"  
          - name: repo-url
            value: "github.com/kagenti/agent-examples.git"
          - name: revision
            value: "main"
          - name: subfolder-path
            value: acp/ollama-deep-researcher
          - name: image
            value: "registry.cr-system.svc.cluster.local:5000/acp-ollama-researcher:v0.0.1"
      cleanupAfterBuild: true
 
  deployer:
    name: "acp-ollama-researcher"
    deployAfterBuild: true
    kubernetes:
      imageSpec:
        image: "acp-ollama-researcher"
        imageTag: "v0.0.1"
        imageRegistry: "registry.cr-system.svc.cluster.local:5000"
        imagePullPolicy: "IfNotPresent"
      containerPorts:
        - name: "http"
          containerPort: 8000
          protocol: "TCP"
      servicePorts:
        - name: "http"
          port: 8000
          targetPort: 8000
          protocol: "TCP"   
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "256M"
      serviceType: "ClusterIP"

    env:
      - name: PORT
        value: "8000"
      - name: HOST
        value: "0.0.0.0"  
      - name: LLM_API_BASE
        value: "http://host.docker.internal:11434/v1"
      - name: LLM_API_KEY
        value: "dummy"  
      - name: LLM_MODEL
        value: "llama3.2:3b-instruct-fp16"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector.kagenti-system.svc.cluster.local:8335  
