apiVersion: beeai.beeai.dev/v1
kind: AgentBuild
metadata:
  labels:
    app.kubernetes.io/name: kagenti-operator
  name: mcp-get-weather
spec:
  repoUrl: "github.com/kagenti/agent-examples.git"
  sourceSubfolder: mcp/weather_tool
  repoUser: ${REPO_USER}
  revision: "main"
  image: "mcp-get-weather"
  imageTag: "v0.0.1"
  imageRegistry: "ghcr.io/${REPO_USER}"
  env:
    - name: "SOURCE_REPO_SECRET"
      valueFrom:
        secretKeyRef:
          name: "github-token-secret"
          key: "token"
  deployAfterBuild: true
  cleanupAfterBuild: true
  agent:
    name: "mcp-get-weather"
    description: "Get current weather for a city"
    env:
      - name: PORT
        value: "8000"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"