apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: open-meteo
  namespace: default
spec:
  hosts:
  - geocoding-api.open-meteo.com
  - api.open-meteo.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS