[project]
name = "researcher"
version = "0.1.0"
description = "researcher crewai agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "crewai",
]
