apiVersion: batch/v1
kind: Job
metadata:
  name: client-registration
spec:
  template:
    spec:
      containers:
      - name: client
        image: client_registration:latest
        imagePullPolicy: Never
        env:
        - name: KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN_USERNAME
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: CLIENT_NAME
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: CLIENT_NAME
      restartPolicy: Never
  backoffLimit: 1
