apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: acp-ollama-researcher 
  labels:
    app: acp-ollama-researcher
spec:
  parentRefs:
    - name: http
      namespace: kagenti-system
  hostnames:
    - "acp-ollama-researcher.localtest.me"
  rules:
    - backendRefs:
        - name: acp-ollama-researcher 
          port: 8000