apiVersion: beeai.beeai.dev/v1
kind: AgentBuild
metadata:
  labels:
    app.kubernetes.io/name: kagenti-operator
    kagenti.io/type: agent
    kagenti.io/protocol: a2a
    kagenti.io/framework: LangGraph
  name: a2a-currency-agent
spec:
  repoUrl: "github.com/kagenti/agent-examples.git"
  sourceSubfolder: a2a/langgraph
  repoUser: ${REPO_USER}
  revision: "main"
  image: "a2a-langgraph-agent" 
  imageTag: "v0.0.1"
  imageRegistry: "ghcr.io/${REPO_USER}" 
  env:
    - name: "SOURCE_REPO_SECRET"
      valueFrom:
        secretKeyRef:
          name: "github-token-secret" 
          key: "token"
  deployAfterBuild: true
  cleanupAfterBuild: true
  agent: 
    name: "a2a-currency-agent" 
    description: "A2A test agent" 
    env: 
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector.kagenti-system.svc.cluster.local:8335  
      - name: "OPENAI_API_KEY"
        valueFrom:
          secretKeyRef:
            name: "openai-secret" 
            key: "apikey"
    resources: 
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"