apiVersion: v1
kind: ConfigMap
metadata:
  name: environments
data:
  ollama: |
    [
      {"name": "LLM_API_BASE", "value": "http://host.docker.internal:11434/v1"},
      {"name": "LLM_API_KEY", "value": "dummy"},
      {"name": "LLM_MODEL", "value": "llama3.2:3b-instruct-fp16"}
    ]
  openai: |
    [
      {
        "name": "OPENAI_API_KEY",
        "valueFrom": {"secretKeyRef": {"name": "openai-secret", "key": "apikey"}}
      }
    ]
  mcp-weather: |
    [
      {"name": "MCP_URL", "value": "http://weather-tool:8000/sse"}
    ]
