apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: acp-weather-service 
  labels:
    app: acp-weather-service
spec:
  parentRefs:
    - name: http
      namespace: kagenti-system
  hostnames:
    - "acp-weather-service.localtest.me"
  rules:
    - backendRefs:
        - name: acp-weather-service
          port: 8000